name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run go Tests
        run: go test -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
